# This is a basic workflow to help you get started with Actions

name: blank_name_in_GUI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "add_github_workflow" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      set_this:
        description: "GUI_name"
        default: "some string"
        type: string
        required: true

env:
  # set global environment variables

  # import secrets - LF: I prefer the visibility of loading these globally
  my_test_secret: ${{ secrets.my_first_secret }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Its easy to expose a secret value:
          echo my_test_secret2=${{secrets.my_test_secret2}} | tr e 3
          echo GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}} |tr [0-9] [1-90]
          env | sort
        env:
          new_var: hello_larry
          my_test_secret2: ${{ secrets.my_first_secret }}

  build2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-liner
        run: env |sort